Added description to the content
unicef/inventory-hugo-theme pull request #146
Opened 2022-07-19 22:23 UTC by Neha9849

This fix is useful for dpg indicators restructure.
If there is no content in a particular DPG indicator then this change will show the description of that page there.

Results:
![image](https://user-images.githubusercontent.com/85057583/179858471-d852ef32-c90b-4cce-9030-6c90b9c97bf1.png)

2022-07-22 03:12 UTC, jwflory requested changes
I like this change. Adding the description to the top of the page is also a nice lead-in for the reader. However, this doesn't work nicely with author bylines (see screenshot below). Could you please check this with the [Data Science & A.I. Toolkit](https://unicef.github.io/ooi-toolkit-ds/privacy-ethics/traps/) as well? These should be on new lines at least.

Once that is fixed, this will be ready to merge. 👍🏻 

![Screenshot of the author bylines appearing on the same line as the article description tag.](https://user-images.githubusercontent.com/4721034/180354508-dec8218f-5b76-455a-9382-ae8d435a81f7.png "Screenshot of the author bylines appearing on the same line as the article description tag.")

2022-07-24 10:50 UTC, Neha9849 commented
I have made this change on the main repo instead of my cloned repo by mistake as I made changes through Github cloud space.
Is that ok?

2022-07-24 10:57 UTC, Neha9849 commented
@jwflory I have added a line break after the author byline.

2022-07-28 13:20 UTC, jwflory requested changes
This change only works if the author's email is set. If an author name is set but not an author email, it still renders on the same line.

![Screenshot of a page with an author name and author email set. The description appears on a new line.](https://user-images.githubusercontent.com/4721034/181514921-7ba780ca-0c41-4a2b-827d-3694d5047fca.png "Screenshot of a page with an author name and author email set. The description appears on a new line.")

![Screenshot of a page with only an author name set. The description appears on the same line.](https://user-images.githubusercontent.com/4721034/181515011-9c852cda-9df7-4b31-b89a-3599c0fe329c.png "Screenshot of a page with only an author name set. The description appears on the same line.")

2022-07-28 13:21 UTC, jwflory commented
@Neha9849 I suggest we use one Bootstrap container for the author information and another container for the text description.

2022-08-01 12:34 UTC, Neha9849 commented
@jwflory I have used containers👍

2022-08-05 14:11 UTC, jwflory approved these changes
Yes! Looks great, both on desktop and also mobile/responsive views. 🚀 Nice work @Neha9849!

Merging! 🎬

2022-08-05 14:14 UTC, merged