🐛 fix: Improved styling of highlight code blocks
unicef/inventory-hugo-theme pull request #72
Opened 2022-03-15 17:51 UTC by BeeBombshell

Fixes #62

Changes:

This PR resolves the styling issue previously faced while using the `highlight` function to create code blocks.

Screenshot of the change:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/53828745/158440519-ac079ae1-ca91-4ccc-aa64-0162d65f64fb.png">

2022-03-16 14:48 UTC, jwflory reviewed
Hey @BeeBombshell, thanks for opening the Pull Request!

I checked this in on the Inventory theme example site and the Open Source Inventory. In both cases, I did not get the expected results.

In the Inventory theme example site, the line numbers match, but there is still a lot of space between each line:

![Screenshot of Code and Syntax Highlighting section, which shows the highlighted sections aligned, but there are still newlines between each line.](https://user-images.githubusercontent.com/4721034/158615393-883b9cf0-9ca1-47c1-af91-cd7b01aa6e65.png "Screenshot of Code and Syntax Highlighting section, which shows the highlighted sections aligned, but there are still newlines between each line.")

In the Open Source Inventory site, the same effect (see [my branch](https://github.com/unicef/inventory/tree/change/highlight-fix-newlines)):

![Screenshot from Maitainer's Guide, which shows the highlighted sections aligned, but there are still newlines between each line.](https://user-images.githubusercontent.com/4721034/158616463-7795f043-27cd-46e9-9e41-677c7b58cbd0.png "Screenshot from Maitainer's Guide, which shows the highlighted sections aligned, but there are still newlines between each line.")

Could you narrow down the root cause for the whitespace showing up? Then this will satisfy #62.

2022-03-17 16:49 UTC, BeeBombshell commented
Hi @jwflory, as I mentioned earlier, there is no in-built `highlight` parameter to change the line spacing of the code... However, I made some changes in the `style.css` file which seem to fix the issue, and the outcome is as follows:

<img width="424" alt="css changes" src="https://user-images.githubusercontent.com/53828745/158851449-84f3d9a5-3dd2-4874-ae0a-1e842cea34c8.png">

2022-03-17 23:26 UTC, jwflory requested changes
Thanks @BeeBombshell, the fix looks good 👍🏻 One request. Could you add a comment above the CSS addition with a link to the original issue, #62? For these CSS changes, it helps to add a short informational comment on why we are making a change the way we are.

Once the comment is in place, I am ready to merge this one 👍🏻

2022-03-18 09:01 UTC, BeeBombshell commented on assets/css/style.css
With reference to #62, added styling to the `highlight` function for improved UI of code blocks.

2022-03-18 15:35 UTC, jwflory approved these changes
Looks good, thanks @BeeBombshell! ✅ Merging this one in. 🌊

2022-03-18 15:36 UTC, merged